### ISSUE TITLE
not broadcasting kick&ban&mute message

### ISSUE THREAD

**Issue by rustyard2021** [thibmo/PlayerAdministration#8]
hello
when i ban or kick a player by F1 commands its broadcast Kicking PlayerName Reason or kicking baning etc..
also when i mute some one betterchatmute broadcast mute time reason everything but when i use this plugin GUI its only ban/kick him without any broadcast system in-game can u fix this problem? thanks

sorry for my bad english

**Comment by rustyard2021** [comment]
and if u can stop key binds when i typing in this gui for search or reason 

i have noclip debug toggle layers vanish binds when i try to type any thing with my keys its calls the commands i have bind in those keys 

again sorry for the bad english

**Comment by thibmo** [comment]
Sadly the input field has a bug for a couple of years now that the game devs keep ignoring, where it doesn't lock the keyboard to just the input. We can't fix this as plugin devs. I heard that you can still hit enter to go into chat, then you can just type and delete the text in the chat after you're done.

Broadcasts can be added when I have some time. (I only support this on best-effort now because someone else took the official support.)

The plugin should interface properly with BetterChatMute, meaning it's broadcasts should work.. (I hope?)
Will have a wee check later, working on requested new plugins right now that have priority.

No worries about your English, I get your points. :)

**Comment by rustyard2021** [comment]
you maintain it again on umod can u fix broadcasting problem?

**Comment by thibmo** [comment]
As soon as I have time again I will have a look at it, I can only guarantee something medio June, if I'm lucky it'll be earlier.
Sadly my day-job has me busy at the moment.

**Comment by rustyard2021** [comment]
we are asking phonix months of months to fix the plugin errors on discord on umod but he didnt do any thing!

**Comment by rustyard2021** [comment]
no problem my mate

**Comment by thibmo** [comment]
I'll not comment on that, as he did pick it up while I was unable to continue support for a while.
But I can see where you're coming from, either tell the people you lost interest, the code is too hard to understand or w/e, don't just stay silent. :)

**Comment by rustyard2021** [comment]
haha when we say fix ban/kick message he share a new update to fix this problem but no didnt fix it + after his update we get more problems i just come back to another version cuz his update didnt fix anything only more bugs im typing to him on his discord server about 3 months and he says fixed but noo

**Comment by rustyard2021** [comment]
thank you for fixing all plugin bugs brodcast problem is not a bug its only a problem for me cuz i want players to see when i mute or ban/kick some one 

it is enough for me that you respond to me when I write that there is a problem . thank you fro your time bro

**Comment by thibmo** [comment]
Yeah, that's why I tagged it as enhancement. It'll probably be a configurable thing. :)

**Comment by rustyard2021** [comment]
Thank you :D

**Comment by thibmo** [comment]
Implemented in 1.6.4
